version: '3'
services:
  web:
    build: ./web
    ports:
      - "80:80"
    volumes:
      - "./data/html:/var/www/html"
  db:
    image: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=zzzzzzzzzzzz
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./data/db:/var/lib/mysql"
  myadmin:
    image: "phpmyadmin/phpmyadmin"
    ports:
      - "8080:80"
