FROM php:5.5-apache

RUN apt-get -y update
RUN apt-get -y -o Dpkg::Options::="--force-confold" install dbconfig-common fontconfig-config fonts-dejavu-core javascript-common libapache2-mod-php5 libfontconfig1 libfreetype6 libgd3 libjbig0 libjpeg62-turbo libjs-jquery libjs-sphinxdoc libjs-underscore libjson-c2 libltdl7 libmcrypt4 libonig2 libpng12-0 libqdbm14 libtiff5 libvpx1 libx11-6 libx11-data libxau6 libxcb1 libxdmcp6 libxpm4 php-gettext php-tcpdf php5-cli php5-gd php5-json php5-mcrypt php5-readline libdbd-mysql-perl libdbi-perl libmysqlclient18 libterm-readkey-perl mysql-client mysql-client-5.5 mysql-common php5-mysql
